### ISSUE TITLE
Gradle errors

### ISSUE THREAD

**Issue by isXander** [Minestom/VanillaReimplementation#10]
default gradle script. 
![s04N8BG](https://user-images.githubusercontent.com/43245524/108627293-af297b80-744c-11eb-9d6a-198e38539179.png)

**Comment by TheMode** [comment]
I believe that it is because we use HTTP instead of HTTPS for sponge repository

**Comment by algj** [comment]
I had error with `org.spongepowered:mixin:0.8`, changing http:// to https:// in `build.gradle`, both in root directory of project and inside Minestom directory.
Then it builds it correctly.
