### ISSUE TITLE
gradle build missing dependencies

### ISSUE THREAD

**Issue by Geoxor** [Minestom/VanillaReimplementation#12]
i tried compiling minestom but it seems that gradle cant fetch the mixin from spongepowered, i dont know enough about how gradle works so i thought i'd share it instead

![image](https://user-images.githubusercontent.com/34042825/111247472-b63d4700-8610-11eb-996b-5144d6cee801.png)

**Comment by jonasled** [comment]
I have the same problem.

**Comment by jonasled** [comment]
To fix this problem you have to edit `Minestorm/build.gradle` and replace `http://repo.spongepowered.org/maven` with  `https://repo.spongepowered.org/maven`
