### ISSUE TITLE
Crafting table inventory

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [Minestom/VanillaReimplementation#30]
Shaped/Shapeless recipes are already loaded and sent to the player inside of the `crafting` module.
Inside of the `crafting` module, add the handling for vanilla crafting table inventory interactions.
Inside of the `blocks` module, add the logic to open the crafting inventory when right clicking the crafting table block.

**Comment by lordtgm** [comment]
I've noticed that shift clicking doesn't work properly. instead of crafting as many as possible, it will move the result of one crafting to the inventory, and no ingredients will be consumed.

**Comment by KrystilizeNevaDies** [comment]
Correct, I will add a follow-up ticket to correctly implement the click handling.
