### ISSUE TITLE
Cannot use on JitPack

### ISSUE THREAD

**Issue by TheKodeToad** [Minestom/VanillaReimplementation#6]
When using JitPack (https://jitpack.io/#Minestom/VanillaReimplementation) the build fails due to trying to build the project with JDK 8. This means you can't add the dependency to Gradle or Maven.

**Comment by YouHaveTrouble** [comment]
It works just fine, it's your IDE trying to force different java version. If you're using IntelliJ go to Run/Debug configurations and make sure JRE is set to java 11 or higher.
